sensitiveCodepaths:
  # Files only allowed authors can modify
  - 'config/database.yml'
  - 'app/controllers/**/*.rb'
allowedAuthors:
  usernames:
    # GitHub username
    # - 'john-doe'
notificationList:
  # GitHub username or team name
  # - '@DryRunSec/security'
  # - '@john-doe'
